services:
  ctfd:
    build: .
    restart: always
    ports:
      - "5000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=postgresql+psycopg2://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      permissions:
        condition: service_completed_successfully
      db:
        condition: service_started
      cache:
        condition: service_started
    networks:
        default:
        internal:

  # TODO: CTFd 4.0 Migrate to named volumes. Users will likely need to manually migrate existing files
  permissions:
    image: alpine:3.23
    user: root
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
    command: chown -R 1001:1001 /var/uploads /var/log/CTFd

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - ctfd

  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ctfd
      - POSTGRES_PASSWORD=ctfd
      - POSTGRES_DB=ctfd
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    networks:
      internal:
      
  cache:
    image: redis:4
    restart: always
    volumes:
      - .data/redis:/data
    networks:
      internal:

networks:
  default:
  internal:
    internal: true