apiVersion: v1
kind: Service
metadata:
  name: cache-redis
  namespace: ctfd
spec:
  clusterIP: 10.233.26.105
  clusterIPs:
  - 10.233.26.105
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
