apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kompose.cmd: ./kompose --file docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kompose.cmd":"./kompose --file docker-compose.yaml convert","kompose.version":"1.34.0 (cbf2835db)"},"labels":{"io.kompose.service":"ctfd"},"name":"ctfd","namespace":"ctfd"},"spec":{"replicas":1,"selector":{"matchLabels":{"io.kompose.service":"ctfd"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"kompose.cmd":"./kompose --file docker-compose.yaml convert","kompose.version":"1.34.0 (cbf2835db)"},"labels":{"io.kompose.service":"ctfd"}},"spec":{"containers":[{"env":[{"name":"ACCESS_LOG","value":"-"},{"name":"DATABASE_URL","value":"mysql+pymysql://ctfd:CTFd%40123%21Secure@10.0.1.5/ctfd"},{"name":"ERROR_LOG","value":"-"},{"name":"LOG_FOLDER","value":"/var/log/CTFd"},{"name":"REDIS_URL","value":"redis://cache:6379"},{"name":"REVERSE_PROXY","value":"true"},{"name":"UPLOAD_FOLDER","value":"/var/uploads"},{"name":"WORKERS","value":"1"}],"image":"ctfd/ctfd:3.7.7","name":"ctfd","ports":[{"containerPort":8000,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/var/log/CTFd","name":"ctfd-claim0"},{"mountPath":"/var/uploads","name":"ctfd-claim1"}]}],"restartPolicy":"Always","volumes":[{"name":"ctfd-claim0","persistentVolumeClaim":{"claimName":"ctfd-claim0"}},{"name":"ctfd-claim1","persistentVolumeClaim":{"claimName":"ctfd-claim1"}}]}}}}
  creationTimestamp: "2025-07-25T13:41:48Z"
  generation: 1
  labels:
    io.kompose.service: ctfd
  name: ctfd
  namespace: ctfd
  resourceVersion: "1122548"
  uid: 88a6390c-0c36-42e6-835c-cf73540dc13c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: ctfd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose --file docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      creationTimestamp: null
      labels:
        io.kompose.service: ctfd
    spec:
      containers:
      - env:
        - name: ACCESS_LOG
          value: '-'
        - name: DATABASE_URL
          value: mysql+pymysql://ctfd:CTFd%40123%21Secure@10.0.1.5/ctfd
        - name: ERROR_LOG
          value: '-'
        - name: LOG_FOLDER
          value: /var/log/CTFd
        - name: REDIS_URL
          value: redis://cache:6379
        - name: REVERSE_PROXY
          value: "true"
        - name: UPLOAD_FOLDER
          value: /var/uploads
        - name: WORKERS
          value: "1"
        image: ctfd/ctfd:3.7.7
        imagePullPolicy: IfNotPresent
        name: ctfd
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/CTFd
          name: ctfd-claim0
        - mountPath: /var/uploads
          name: ctfd-claim1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ctfd-claim0
        persistentVolumeClaim:
          claimName: ctfd-claim0
      - name: ctfd-claim1
        persistentVolumeClaim:
          claimName: ctfd-claim1
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-25T13:41:49Z"
    lastUpdateTime: "2025-07-25T13:41:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-25T13:41:48Z"
    lastUpdateTime: "2025-07-25T13:41:49Z"
    message: ReplicaSet "ctfd-7b5fff4764" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
