apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-uploads-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeMode: Filesystem
