apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  name: ctfd-deploy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - env:
        - name: ACCESS_LOG
          value: '-'
        - name: DATABASE_URL
          value: mysql+pymysql://ctfd:CTFd%40123%21Secure@10.0.1.5/ctfd
        - name: ERROR_LOG
          value: '-'
        - name: LOG_FOLDER
          value: /var/log/CTFd
        - name: REDIS_URL
          value: redis://cache:6379
        - name: REVERSE_PROXY
          value: "true"
        - name: UPLOAD_FOLDER
          value: /var/uploads
        - name: WORKERS
          value: "1"
        image: ctfd/ctfd:3.7.7
        imagePullPolicy: IfNotPresent
        name: ctfd
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/CTFd
          name: ctfd-claim0
        - mountPath: /var/uploads
          name: ctfd-claim1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ctfd-claim00
        persistentVolumeClaim:
          claimName: ctfd-claim000
      - name: ctfd-claim01
        persistentVolumeClaim:
          claimName: ctfd-claim01
