apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"io.kompose.service":"ctfd-claim1"},"name":"ctfd-claim1","namespace":"ctfd"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"100Mi"}}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2025-07-25T10:34:05Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    io.kompose.service: ctfd-claim1
  name: ctfd-claim1
  namespace: ctfd
  resourceVersion: "1042567"
  uid: 30412875-abe9-47c3-b0d6-cbc5c2542fe6
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-30412875-abe9-47c3-b0d6-cbc5c2542fe6
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  phase: Bound
