apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-claim01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
