apiVersion: v1
kind: Service
metadata:
  name: ctfd-svc
spec:
  ports:
  - name: "8000"
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    io.kompose.service: ctfd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
