apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx  # Added consistent label
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx  # Required selector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx  # Must match selector
    spec:
      containers:
      - image: nginx:stable
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "0.4"
            memory: "128Mi"
          limits:
            cpu: "1"
            memory: "256Mi"
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: http.conf
      volumes:
      - configMap:
          name: nginx-config
        name: nginx-config
