apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim00
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
  volumeMode: Filesystem
