apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/publicEndpoints: '[{"addresses":["10.0.1.240"],"port":80,"protocol":"HTTP","serviceName":"ctfd:nginx","ingressName":"ctfd:ctfd-ingress","hostname":"ctfd.app.r2b001.site","path":"/","allNodes":false}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"io.kompose.service":"nginx"},"name":"nginx","namespace":"ctfd"},"spec":{"replicas":1,"selector":{"matchLabels":{"io.kompose.service":"nginx"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"io.kompose.service":"nginx"}},"spec":{"containers":[{"image":"nginx:stable","name":"nginx","ports":[{"containerPort":80}],"volumeMounts":[{"mountPath":"/etc/nginx/nginx.conf","name":"nginx-config","subPath":"http.conf"}]}],"volumes":[{"configMap":{"items":[{"key":"http.conf","path":"http.conf"}],"name":"nginx-config"},"name":"nginx-config"}]}}}}
  creationTimestamp: "2025-07-25T10:35:23Z"
  generation: 3
  labels:
    io.kompose.service: nginx
  name: nginx
  namespace: ctfd
  resourceVersion: "1126009"
  uid: d2841232-945f-4efc-bb6b-6ba965810e2d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: nginx:stable
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: http.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: http.conf
            path: http.conf
          name: nginx-config
        name: nginx-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-25T11:05:05Z"
    lastUpdateTime: "2025-07-25T11:05:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-25T11:05:02Z"
    lastUpdateTime: "2025-07-25T11:05:05Z"
    message: ReplicaSet "nginx-6d9fbc7d59" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
