apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx  # Added consistent label
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx  # Required selector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx  # Must match selector
    spec:
      containers:
      - image: nginx:stable
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config

      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
