apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose --file docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kompose.cmd":"./kompose --file docker-compose.yaml convert","kompose.version":"1.34.0 (cbf2835db)"},"labels":{"io.kompose.service":"nginx"},"name":"nginx","namespace":"ctfd"},"spec":{"ports":[{"name":"80","port":80,"targetPort":80}],"selector":{"io.kompose.service":"nginx"}}}
  creationTimestamp: "2025-07-24T22:07:31Z"
  labels:
    io.kompose.service: nginx
  name: nginx
  namespace: ctfd
  resourceVersion: "1043191"
  uid: 63d58fce-da07-44ff-9fa1-100da08c148e
spec:
  clusterIP: 10.233.46.107
  clusterIPs:
  - 10.233.46.107
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    io.kompose.service: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
