"""Add modules and audiences

Revision ID: 336b8c601b94
Revises: 48d8250d19bd
Create Date: 2026-06-29 06:22:11.875090

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "336b8c601b94"
down_revision = "48d8250d19bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audiences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "modules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audience_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("audience_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["audience_id"], ["audiences.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("audience_id", "team_id", name="uq_audience_team"),
        sa.UniqueConstraint("audience_id", "user_id", name="uq_audience_user"),
    )
    op.create_table(
        "module_audience_access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("audience_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["audience_id"], ["audiences.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["module_id"], ["modules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("module_id", "audience_id", name="uq_module_audience"),
    )
    op.add_column("challenges", sa.Column("module_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "challenges", "modules", ["module_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "challenges", type_="foreignkey")
    op.drop_column("challenges", "module_id")
    op.drop_table("module_audience_access")
    op.drop_table("audience_members")
    op.drop_table("modules")
    op.drop_table("audiences")
    # ### end Alembic commands ###
