"""Add challenge logic column

Revision ID: 4eca07c39397
Revises: a49ad66aa0f1
Create Date: 2025-05-29 21:17:59.428697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4eca07c39397"
down_revision = "a49ad66aa0f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "challenges",
        sa.Column("logic", sa.String(length=80), nullable=False, server_default="any"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("challenges", "logic")
    # ### end Alembic commands ###
