"""Add connection_info column to Challenges

Revision ID: 95d243b9ca50
Revises: 07dfbe5e1edc
Create Date: 2021-07-30 02:11:53.366162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95d243b9ca50"
down_revision = "07dfbe5e1edc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("challenges", sa.Column("connection_info", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("challenges", "connection_info")
    # ### end Alembic commands ###
