"""Add cascading delete to dynamic challenges

Revision ID: b37fb68807ea
Revises: 1093835a1051
Create Date: 2020-05-06 12:21:39.373983

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b37fb68807ea'
down_revision = '1093835a1051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dynamic_challenge', type_='foreignkey')
    op.create_foreign_key(None, 'dynamic_challenge', 'challenges', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dynamic_challenge', type_='foreignkey')
    op.create_foreign_key(None, 'dynamic_challenge', 'challenges', ['id'], ['id'])
    # ### end Alembic commands ###
