"""add group_type to users and teams

Revision ID: b7a05d39df5b
Revises: a02c5bf43407
Create Date: 2024-04-03 20:09:33.513123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a05d39df5b'
down_revision = 'a02c5bf43407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('group_type', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('extra_info', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('group_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group_type')
    op.drop_column('users', 'extra_info')
    op.drop_column('teams', 'group_type')
    # ### end Alembic commands ###
