"""Adding member,number to teams

Revision ID: d5a224bf5864
Revises: d5a224bf5863
Create Date: 2018-1-2 00:00:00.00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd5a224bf5864'
down_revision = 'd5a224bf5863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('member', sa.String(length=64), nullable=True, default=0))
    op.add_column('teams', sa.Column('number', sa.String(length=64), nullable=True, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'member')
    op.drop_column('teams', 'number')
    # ### end Alembic commands ###
