"""Add captain to Teams

Revision ID: d72b10c3c1e7
Revises: 4e4d5a9ea000
Create Date: 2019-04-11 23:57:38.076964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd72b10c3c1e7'
down_revision = '4e4d5a9ea000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('captain_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['captain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'captain_id')
    # ### end Alembic commands ###
