"""Add IP column to Unlocks

Revision ID: f63a9205d72f
Revises: 8275865e5992
Create Date: 2026-08-31 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f63a9205d72f"
down_revision = "8275865e5992"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("unlocks", sa.Column("ip", sa.String(length=46), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("unlocks", "ip")
    # ### end Alembic commands ###
