#coding=utf-8
lang_en = {
'SMTP_TIME_OUT':'SMTP server connection timed out',
'MAIL_SENT':'Email sent',
'MAILGUN_MISS':'Mailgun settings are missing',
'MAILGUN_EXECPTION':'{error} exception occured while handling your request',
'MAILGUN_ERR_SET':'Mailgun settings are incorrect',
'MAIL_MSG_FORM':'Message from {0}',
'MAIL_MSG_TEXT':'Please click the following link to confirm your email address for {ctf_name}: {url}/{token}\n\nYour Team-Token is [{team_token}] Please save it',
'MAIL_MSG_FORGOT':'Did you initiate a password reset? Click the following link to reset your password:\n\n{0}/{1}\n\n',
'INVIDE_USER_PASS':'Your username or password is incorrect',
'INVIDE_USER':'[{date}] {ip} - submitted invalid account information',
'INVIDE_PASS':'[{date}] {ip} - submitted invalid password for {username}',
'USER_LOGINED':'[{date}] {ip} - {username} logged in',
'USER_REGISTRED':'[{date}] {ip} - {username} registered with {email}',
'USER_REG_SUCCESS':"You've successfully registered for {}",
'USER_REG_WARN':'[{date}] {ip} - {username} registered (UNCONFIRMED) with {email}',
'INVIDE_EMAIL':'Please enter a valid email address',
'TOO_SHORT_TEAM':'Pick a longer team name',
'TOO_LONG_PASS':'Pick a shorter password',
'TOO_SHORT_PASS':'Pick a longer password',
'EMAIL_HAVE_USE':'Email has already been used',
'EMAIL_NOT_TEAM':'Team name cannot be an email address',
'TEAM_EXIST':'That team name is already taken',
'FORGOT_PASS_NOTICE':'If that account exists you will receive an email, please check your inbox',
'EMAIL_NOT_CONFIG':'Email could not be sent due to server misconfiguration',
'PASS_HAVE_RESET':'[{date}] {ip} -  successful password reset for {username}',
'LINK_EXPIRED':'Your link has expired',
'INVIDE_RESET_TOKEN':'Your reset token is invalid',
'EMAIL_CF_SENT':'Your confirmation email has been resent!',
'EMAIL_CF_RESENT':'[{date}] {ip} - {username} initiated a confirmation email resend',
'USER_HAVE_CM':'[{date}] {ip} - {username} confirmed their account',
'NOT_ENOUGH_POINT':'Not enough points',
'HIT_FOR':'Hint for {}',
'IS_PAUSED':'{} is paused',
'NOT_START':'{} has not started yet',
'HAS_END':'{} has ended',
'SUBMIT_TOO_FAST':"You're submitting keys too fast. Slow down.",
'ZERO_CAN_TRY':"You have 0 tries remaining",
'MANY_CAN_TRY':'{} You have {} {} remaining.',
'HAVE_SOLVE':'You already solved this',
'MUST_LOGGED':'You must be logged in to solve a challenge',
'SCORE_HIDDEN':'Scores are currently hidden',
'MISS_URL_ROUTE':'Missing URL route',
'SEARCH_ERROR1':'Your ID search term is not numeric',
'NEED_TEAM_NAME':'The team requires a name',
'NEED_TEAM_EMAIL':'The team requires an email',
'NEED_TEAM_PASS':'The team requires a password',
'INVIDE_LINK_FORMAT':'Websites must start with http:// or https://',
'MISS_INFO':"Missing information",
'T_CORRECT':"Correct",
'T_INCORRECT':"Incorrect",
'PASS_NOT_MATCH':"Your old password doesn't match what we have."
}
lang_zh_cn = {
'SMTP_TIME_OUT':'连接SMTP服务器超时,请检查端口是否被禁用',
'MAIL_SENT':'邮件已发送',
'MAILGUN_MISS':'Mailgun未设置',
'MAILGUN_EXECPTION':'请求时发生错误 {error}',
'MAILGUN_ERR_SET':'Mailgun 设置错误',
'MAIL_MSG_FORM':'您有一封来自 {0} 的邮件',
'MAIL_MSG_TEXT':'请点击下面的链接确认您在 {ctf_name} 的邮箱: {url}/{token}\n\n您的 Team-Token 是 [{team_token}] 请妥善保存',
'MAIL_MSG_FORGOT':'确定重置密码? 请点击下面的链接重置您的密码:\n\n{0}/{1}\n\n',
'INVIDE_USER_PASS':'用户名或密码错误',
'INVIDE_USER':'[{date}] {ip} - submitted invalid account information',
'INVIDE_PASS':'[{date}] {ip} - submitted invalid password for {username}',
'USER_LOGINED':'[{date}] {ip} - {username} logged in',
'USER_REGISTRED':'[{date}] {ip} - {username} registered with {email}',
'USER_REG_SUCCESS':"您已经成功注册 {}",
'USER_REG_WARN':'[{date}] {ip} - {username} registered (UNCONFIRMED) with {email}',
'INVIDE_EMAIL':'请输入一个有效的邮箱地址',
'TOO_SHORT_TEAM':'战队名太短',
'TOO_LONG_PASS':'密码太长',
'TOO_SHORT_PASS':'密码太短',
'EMAIL_HAVE_USE':'邮箱地址已被使用',
'EMAIL_NOT_TEAM':'战队名不能是邮箱地址',
'TEAM_EXIST':'战队名已经被抢先注册了',
'FORGOT_PASS_NOTICE':'如果账户信息填写正确,您将会收到一条邮件',
'EMAIL_NOT_CONFIG':'邮箱系统未配置,请联系管理员',
'PASS_HAVE_RESET':'[{date}] {ip} -  successful password reset for {username}',
'LINK_EXPIRED':'您的链接已经过期了哦',
'INVIDE_RESET_TOKEN':'您的重置口令不对哦',
'EMAIL_CF_SENT':'您的验证邮件已经重新发送!',
'EMAIL_CF_RESENT':'[{date}] {ip} - {username} initiated a confirmation email resend',
'USER_HAVE_CM':'[{date}] {ip} - {username} confirmed their account',
'NOT_ENOUGH_POINT':'没有足够的分值',
'HIT_FOR':'Hint for {}',
'IS_PAUSED':'{} 已经暂停',
'NOT_START':'{} 还没开始',
'HAS_END':'{} 已经停止',
'SUBMIT_TOO_FAST':"神了,这么快,再等会再提交吧!",
'ZERO_CAN_TRY':"您的尝试次数已用完",
'MANY_CAN_TRY':'{} 您还剩 {} {} 机会.',
'HAVE_SOLVE':'您已经解决该问题了',
'MUST_LOGGED':'必须登陆才可以答题哦',
'SCORE_HIDDEN':'当前分数已隐藏',
'MISS_URL_ROUTE':'Missing URL route',
'SEARCH_ERROR1':'ID是一个数值哦',
'NEED_TEAM_NAME':'战队怎么能没名字呢?',
'NEED_TEAM_EMAIL':'战队怎么能没邮箱呢?',
'NEED_TEAM_PASS':'战队怎么能没密码呢?',
'INVIDE_LINK_FORMAT':'网址必须以 http:// 或 https:// 开头',
'MISS_INFO':"信息丢失",
'T_CORRECT':"Correct",
'T_INCORRECT':"Incorrect",
'PASS_NOT_MATCH':"原密码错误"
}
langs = {'en': lang_en,'zh_cn':lang_zh_cn}
  