---
name: Theme Verification

on:
  push:
    branches:
      - master
    paths:
      - 'CTFd/themes/**'
  pull_request:
    branches:
      - master
    paths:
      - 'CTFd/themes/**'

jobs:
  build:

    runs-on: ubuntu-latest

    name: Theme Verification
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: yarn
          cache-dependency-path: |
            CTFd/themes/admin/yarn.lock
            CTFd/themes/core/yarn.lock

      - name: Verify admin theme
        run: |
            pwd
            yarn install --frozen-lockfile
            yarn verify
        working-directory: ./CTFd/themes/admin

      # TODO: Replace in 4.0 with deprecation of previous core theme
      - name: Verify core theme
        run: |
            pwd
            yarn install --frozen-lockfile
            yarn verify
        working-directory: ./CTFd/themes/core
