---
name: Theme Verification

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    name: Theme Verification
    steps:
      - uses: actions/checkout@v2
      - name: Verify admin theme
        run: |
            cd CTFd/themes/admin
            yarn install --non-interactive
            yarn verify 

      # TODO: Replace in 4.0 with deprecation of previous core theme
      - name: Verify core-beta theme
        run: |
            cd CTFd/themes/core-beta
            yarn install --non-interactive
            yarn verify
